# Generated by Django 2.2 on 2023-03-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0004_products_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
