# Generated by Django 2.2 on 2023-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0005_auto_20230401_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=250, unique=True),
        ),
    ]
